spring:
  application:
    name: service-registry

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: "configserver:"

  cloud:
    config:
      # uri: http://config.platform:9000
       uri: http://localhost:9000
